# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-26 16:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noWaster', '0002_auto_20180326_1938'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loc',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
