# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-26 16:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noWaster', '0003_auto_20180326_1953'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loc',
            options={},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
