# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-26 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('noWaster', '0006_auto_20180326_2004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loc',
            fields=[
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('id', models.AutoField(db_column=b'ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'loc',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('test', models.CharField(max_length=30)),
                ('id', models.AutoField(db_column=b'ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'test',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('id', models.AutoField(db_column=b'ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
