# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-26 17:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noWaster', '0007_loc_test_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
