# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-26 17:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noWaster', '0008_delete_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Loc',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
