# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-26 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noWaster', '0011_auto_20180326_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(db_column=b'ID', db_index=True, max_length=20, primary_key=True, serialize=False),
        ),
    ]
