# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-27 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noWaster', '0012_auto_20180326_2030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AddField(
            model_name='user',
            name='last_interaction_time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='origin_loc_address',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='origin_loc_lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='origin_loc_lng',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='stage',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
