# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-27 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noWaster', '0014_user_currently_responding_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dest_loc_address',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='dest_loc_lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='dest_loc_lng',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='stage',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
