# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-29 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noWaster', '0016_auto_20180327_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_update_time',
            field=models.TimeField(null=True),
        ),
    ]
