# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-29 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noWaster', '0018_auto_20180329_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_update_time',
            field=models.DateField(null=True),
        ),
    ]
