# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-29 13:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noWaster', '0020_auto_20180329_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_update_time',
        ),
    ]
