# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-02 08:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noWaster', '0023_auto_20180330_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emoji',
            fields=[
                ('id', models.IntegerField(db_column=b'ID', primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'emoji',
                'verbose_name': 'emoji',
                'verbose_name_plural': 'emojis',
            },
        ),
        migrations.CreateModel(
            name='WeatherDictionary',
            fields=[
                ('id', models.IntegerField(db_column=b'ID', primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=20)),
                ('emoji1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emoji1', to='noWaster.Emoji')),
                ('emoji2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emoji2', to='noWaster.Emoji')),
            ],
            options={
                'db_table': 'weather',
                'verbose_name': 'weather',
            },
        ),
        migrations.AlterModelOptions(
            name='loc',
            options={'verbose_name': 'location', 'verbose_name_plural': 'locations'},
        ),
        migrations.AlterField(
            model_name='loc',
            name='address',
            field=models.CharField(blank=True, default=b'', max_length=100),
        ),
        migrations.AlterField(
            model_name='loc',
            name='name',
            field=models.CharField(blank=True, default=b'', max_length=50),
        ),
    ]
